name: CI (Continue Integrations)

on: workflow_dispatch

jobs:

    #id job
    build-testing: #Pastikan gak ada spasi
        name: Build and Testing
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: Create .env file
              run: |
                echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
                echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
                echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
                echo "POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}" >> .env
                echo "POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}" >> .env

            - name: Install Docker Compose
              run: |
                sudo apt-get update
                sudo apt-get install -y docker-compose

            - name: Build and Run Container
              run: |
                sudo docker-compose --env-file .env up -d

            - name: Install requirements for testing
              run: |
                pip install -r testing/requirements.txt

            - name: Testing
              run: |
                sleep 20
                curl localhost:5000
                pytest testing/test.py




